# ==============================================================================
# Script: Rsamtools_softclipseq_FR_github.R
# Description:
#   This script processes the tab-delimited output files generated by
#   Rsamtools_FR_github.R (both Hwenjian and Lwenjian files). For
#   each sample, it computes four summary tables:
#     1. Distribution of base length (0–30 bp)
#     2. Base composition of soft-clip sequences
#     3. Terminal base of the first base of soft-clips
#     4. Distribution pattern of soft-clip presence on R1 and R2 (both, only R1, only R2)
#   Results are saved as separate tables in subdirectories under the output
#   base directory.
# Input:
#   "_Hwenjian.txt" and "_Lwenjian.txt"
# Output:
#   "_H_Snumber_table.txt", "_H_Sbase_table.txt", "_H_Sb_table.txt" and "_H_type3_table.txt"
#   "_L_Snumber_table.txt", "_L_Sbase_table.txt", "_L_Sb_table.txt" and "_L_type3_table.txt"
# Usage: Rscript Rsamtools_softclipseq_FR_github.R
# ==============================================================================




# ------------------------------------------------------------------------------
# Part 1: Process H-strand files (flags 99 & 147 pairs)
# ------------------------------------------------------------------------------


# Define input and output paths
input_dir <- "D:/run/Hwenjian/"
output_base <- "D:/run/softclipseq/"

# Create output subdirectories for H-strand files
for(dir_name in c("H_Snumber_table", "H_Sbase_table", "H_Sb_table", "H_type3_table")) {
  dir.create(file.path(output_base, dir_name), recursive = TRUE, showWarnings = FALSE)
}

# Get list of H-strand files
ff1 <- list.files(input_dir, pattern = "_Hwenjian.txt$")

# Process each H-strand file
for(i in 1:length(ff1)) {
  # Read data
  H <- read.table(paste(input_dir, ff1[i], sep = ""), sep = "\t", head = TRUE)
  num_H <- nrow(H)
  
  # 1. Distribution of base length
  H_Snumber_tab <- as.data.frame(table(cut(na.omit(c(H$R1S5number, H$R2S5number)), 
                                           breaks = seq(0, 30, by = 1), 
                                           right = FALSE, include.lowest = TRUE)))
  H_Snumber_table <- H_Snumber_tab[-1,]
  H_Snumber_table[,3] <- H_Snumber_table[,2] / sum(H_Snumber_table[,2])
  colnames(H_Snumber_table) <- c("Type","Number","Proportion")
  
  # 2. Base composition of all soft-clip sequences
  H_Sbase <- c(H$R1S5base, H$R2S5base)
  H_Sbase_seq <- paste(H_Sbase, collapse = "")
  H_Sbase_table <- table(strsplit(H_Sbase_seq, "")[[1]])
  H_Sbase_table <- as.data.frame(H_Sbase_table)
  H_Sbase_table <- H_Sbase_table[!grepl("N", H_Sbase_table$Var1), ]
  H_Sbase_table[,3] <- H_Sbase_table[,2]/sum(H_Sbase_table[,2])
  colnames(H_Sbase_table) <- c("base1234","H_number","H_proportion")
  
  # 3. Terminal base of the first base of soft-clips (only for reads with soft-clip)
  H_R11 <- subset(H, H$R1S5type != 0)
  H_R21 <- subset(H, H$R2S5type != 0)
  H_Sb <- c(H_R11$R1S5b1, H_R21$R2S5b1)
  H_Sb_seq <- paste(H_Sb, collapse = "")
  H_Sb_table <- table(strsplit(H_Sb_seq, "")[[1]])
  H_Sb_table <- as.data.frame(H_Sb_table)
  H_Sb_table <- H_Sb_table[!grepl("N", H_Sb_table$Var1), ]
  H_Sb_table[,3] <- H_Sb_table[,2]/sum(H_Sb_table[,2])
  colnames(H_Sb_table) <- c("base1234","H_number","H_proportion")
  
  # 4. Distribution pattern
  H11 <- subset(H, H$R1S5type != 0 & H$R2S5type != 0)
  numberH11 <- length(H11[,1])
  H10 <- subset(H, H$R1S5type != 0 & H$R2S5type == 0)
  numberH10 <- length(H10[,1])
  H01 <- subset(H, H$R1S5type == 0 & H$R2S5type != 0)
  numberH01 <- length(H01[,1])
  H_type3_table <- rbind(numberH11, numberH10, numberH01)
  H_type3_table <- as.data.frame(H_type3_table)
  H_type3_table[,2] <- H_type3_table[,1]/sum(H_type3_table[,1])
  H_type3_table <- cbind(row_names = rownames(H_type3_table), H_type3_table)
  colnames(H_type3_table) <- c("Htype3","Hnumber","Hproportion")
  
  # Output file prefix
  file_prefix <- sub("_Hwenjian.txt", "", ff1[i])
  
  # Write each table to its corresponding subdirectory
  write.table(H_Snumber_table, 
              file.path(output_base, "H_Snumber_table", paste0(file_prefix, "_H_Snumber_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
  
  write.table(H_Sbase_table,
              file.path(output_base, "H_Sbase_table", paste0(file_prefix, "_H_Sbase_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
  
  write.table(H_Sb_table,
              file.path(output_base, "H_Sb_table", paste0(file_prefix, "_H_Sb_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
  
  write.table(H_type3_table,
              file.path(output_base, "H_type3_table", paste0(file_prefix, "_H_type3_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
}




# ------------------------------------------------------------------------------
# Part 2: Process L-strand files (flags 163 & 83 pairs)
# ------------------------------------------------------------------------------


# Define input and output paths
input_dir <- "D:/run/Lwenjian/"
output_base <- "D:/run/softclipseq/"

# Create output subdirectories for L-strand files
for(dir_name in c("L_Snumber_table", "L_Sbase_table", "L_Sb_table", "L_type3_table")) {
  dir.create(file.path(output_base, dir_name), recursive = TRUE, showWarnings = FALSE)
}

# Get list of L-strand files
ff1 <- list.files(input_dir, pattern = "_Lwenjian.txt$")

# Process each L-strand file
for(i in 1:length(ff1)) {
  # Read data
  L <- read.table(paste(input_dir, ff1[i], sep = ""), sep = "\t", head = TRUE)
  num_L <- nrow(L)
  
  # 1. Distribution of base length
  L_Snumber_tab <- as.data.frame(table(cut(na.omit(c(L$R1S5number, L$R2S5number)), 
                                           breaks = seq(0, 30, by = 1), 
                                           right = FALSE, include.lowest = TRUE)))
  L_Snumber_table <- L_Snumber_tab[-1,]
  L_Snumber_table[,3] <- L_Snumber_table[,2] / sum(L_Snumber_table[,2])
  colnames(L_Snumber_table) <- c("Type","Number","Proportion")
  
  # 2. Base composition of all soft-clip sequences
  L_Sbase <- c(L$R1S5base, L$R2S5base)
  L_Sbase_seq <- paste(L_Sbase, collapse = "")
  L_Sbase_table <- table(strsplit(L_Sbase_seq, "")[[1]])
  L_Sbase_table <- as.data.frame(L_Sbase_table)
  L_Sbase_table <- L_Sbase_table[!grepl("N", L_Sbase_table$Var1), ]
  L_Sbase_table[,3] <- L_Sbase_table[,2]/sum(L_Sbase_table[,2])
  colnames(L_Sbase_table) <- c("base1234","L_number","L_proportion")
  
  # 3. Terminal base of the first base of soft-clips (only for reads with soft-clip)
  L_R11 <- subset(L, L$R1S5type != 0)
  L_R21 <- subset(L, L$R2S5type != 0)
  L_Sb <- c(L_R11$R1S5b1, L_R21$R2S5b1)
  L_Sb_seq <- paste(L_Sb, collapse = "")
  L_Sb_table <- table(strsplit(L_Sb_seq, "")[[1]])
  L_Sb_table <- as.data.frame(L_Sb_table)
  L_Sb_table <- L_Sb_table[!grepl("N", L_Sb_table$Var1), ]
  L_Sb_table[,3] <- L_Sb_table[,2]/sum(L_Sb_table[,2])
  colnames(L_Sb_table) <- c("base1234","L_number","L_proportion")
  
  # 4. Distribution pattern
  L11 <- subset(L, L$R1S5type != 0 & L$R2S5type != 0)
  numberL11 <- length(L11[,1])
  L10 <- subset(L, L$R1S5type != 0 & L$R2S5type == 0)
  numberL10 <- length(L10[,1])
  L01 <- subset(L, L$R1S5type == 0 & L$R2S5type != 0)
  numberL01 <- length(L01[,1])
  L_type3_table <- rbind(numberL11, numberL10, numberL01)
  L_type3_table <- as.data.frame(L_type3_table)
  L_type3_table[,2] <- L_type3_table[,1]/sum(L_type3_table[,1])
  L_type3_table <- cbind(row_names = rownames(L_type3_table), L_type3_table)
  colnames(L_type3_table) <- c("Ltype3","Lnumber","Lproportion")
  
  # Output file prefix
  file_prefix <- sub("_Lwenjian.txt", "", ff1[i])
  
  # Write each table to its corresponding subdirectory
  write.table(L_Snumber_table, 
              file.path(output_base, "L_Snumber_table", paste0(file_prefix, "_L_Snumber_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
  
  write.table(L_Sbase_table,
              file.path(output_base, "L_Sbase_table", paste0(file_prefix, "_L_Sbase_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
  
  write.table(L_Sb_table,
              file.path(output_base, "L_Sb_table", paste0(file_prefix, "_L_Sb_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
  
  write.table(L_type3_table,
              file.path(output_base, "L_type3_table", paste0(file_prefix, "_L_type3_table.txt")),
              sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
}



